import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const stylesheetPath = fileURLToPath(new URL('../style.css', import.meta.url));
const htmlPath = fileURLToPath(new URL('../index.html', import.meta.url));
const scriptPath = fileURLToPath(new URL('../app.js', import.meta.url));

describe('test console stylesheet', () => {
  it('defines the base layout, editor and responsive rules', async () => {
    const stylesheet = await readFile(stylesheetPath, 'utf8');
    const html = await readFile(htmlPath, 'utf8');
    const script = await readFile(scriptPath, 'utf8');

    expect(stylesheet).toContain(':root');
    expect(stylesheet).toContain('.sidebar');
    expect(stylesheet).toContain('.workspace-grid');
    expect(stylesheet).toContain('.case-editor');
    expect(stylesheet).toContain('.asset-selection');
    expect(stylesheet).toContain('.asset-toolbar { display: grid; grid-template-columns: minmax(260px, 1fr) 180px 36px;');
    expect(stylesheet).toContain('.asset-toolbar select { width: 180px; height: 36px; }');
    expect(stylesheet).toContain('.batch-history');
    expect(stylesheet).toContain('.route-view');
    expect(stylesheet).toContain('.assets-table');
    expect(html).toContain('#/dashboard');
    expect(html).toContain('#/assets');
    expect(html).toContain('data-route-view="dashboard"');
    expect(html).toContain('data-route-view="asset-editor"');
    expect(html).toContain('id="assetSearch"');
    expect(html).not.toContain('社区 CMS');
    expect(html).toContain('id="projectList"');
    expect(html).toContain('id="createProject"');
    expect(html).toContain('id="caseProjectId"');
    expect(html).toContain('id="deleteCase"');
    expect(html).toContain('id="newWebCaseLink"');
    expect(html).toContain('id="newApiCaseLink"');
    expect(html).toContain('id="assetTargetFilter"');
    expect(html).toContain('id="selectAllCases"');
    expect(html).toContain('id="deleteSelectedCases"');
    expect(html).toContain('id="apiSteps"');
    expect(html).toContain('id="debugApiCase"');
    expect(html).toContain('id="apiRequestPreview"');
    expect(html).toContain('id="batchHistoryList"');
    expect(html).toContain('data-dashboard-range="7d"');
    expect(html).toContain('href="#/executions"');
    expect(html).toContain('href="#/reports"');
    expect(html).toContain('data-route-view="executions"');
    expect(html).toContain('data-route-view="reports"');
    expect(html).toContain('id="executionProject"');
    expect(html).toContain('id="reportProject"');
    expect(html).toContain('<option value="">全部项目</option>');
    expect(script).toContain('async function loadProjectFilters()');
    expect(script).toContain("$('#executionProject')");
    expect(script).toContain("$('#reportProject')");
    expect(script).toContain("query.set('projectId', $('#executionProject').value)");
    expect(script).toContain("query.set('projectId', $('#reportProject').value)");
    expect(script).toContain('selectedExecutionId = tasks[0]?.id || null');
    expect(script).toContain("$('#executionProject').addEventListener('change'");
    expect(script).toContain("$('#reportProject').addEventListener('change'");
    expect(script).toContain("fetch('/api/projects')");
    expect(html).toContain('id="dashboardTrend"');
    expect(html).toContain('先锋营自动化测试平台');
    expect(html).toContain('id="loginForm"');
    expect(html).toContain('id="currentUserButton"');
    expect(html).toContain('data-route-view="profile"');
    expect(html).not.toContain('Atlas Commerce');
    expect(html).not.toContain('当前空间');
    expect(html).not.toContain('NovaTest');
    expect(stylesheet).toContain('.login-screen');
    expect(stylesheet).toContain('.login-screen[hidden] { display: none; }');
    expect(stylesheet).toContain('.profile-grid');
    expect(script).toContain('async function restoreSession()');
    expect(script).toContain("fetch('/api/auth/session')");
    expect(script).toContain("fetch('/api/auth/login'");
    expect(script).toContain("fetch('/api/auth/profile'");
    expect(script).toContain("fetch('/api/auth/password'");
    expect(script).toContain("fetch('/api/auth/logout'");
    expect(html).toContain('id="dashboardTargetBreakdown"');
    expect(html).toContain('class="dashboard-chart chart-empty"');
    expect(script).toContain('function renderDashboardTrend(');
    expect(script).toContain('function renderDashboardTargetBreakdown(');
    expect(script).toContain('function createDashboardDonut(');
    expect(script).toContain("svg.setAttribute('role', 'img')");
    expect(script).toContain('function nonNegativeNumber(');
    expect(script).toContain("'所选时间范围内暂无已完成执行记录'");
    expect(script).toContain("target === 'web'");
    expect(script).toContain("target === 'api'");
    expect(script).toContain('const maxDailyTotal = Math.max(');
    expect(script).toContain("svg.setAttribute('aria-label', ariaLabel)");
    expect(script).toContain('window.requestAnimationFrame(() => {');
    expect(stylesheet).toContain('.dashboard-chart');
    expect(stylesheet).toContain('.dashboard-donut');
    expect(stylesheet).toContain('.dashboard-daily-bars');
    expect(stylesheet).toContain('.dashboard-chart-content');
    expect(stylesheet).toContain('.dashboard-donut-segment { transition: stroke-dasharray .45s ease, stroke-dashoffset .45s ease; }');
    expect(stylesheet).toContain('.dashboard-daily-bar-fill { transition: height .45s ease; }');
    expect(stylesheet).toContain('.dashboard-target-chart');
    expect(stylesheet).toContain('.dashboard-daily-scroll');
    expect(html).not.toContain('id="runLog"');
    expect(script).toContain('function startExecutionPolling()');
    expect(script).toContain('async function loadReports()');
    expect(script).toContain('function getExecutionConclusion(');
    expect(script).toContain('async function loadExecutionDetail(');
    expect(script).toContain('function renderExecutionDetail(');
    expect(stylesheet).toContain('.execution-conclusion');
    expect(stylesheet).toContain('.execution-timeline');
    expect(script).toContain('function renderRoute()');
    expect(script).toContain('async function loadEditor');
    expect(script).toContain('async function deleteEditor');
    expect(script).toContain('function readApiCaseFromForm()');
    expect(script).toContain('function renderApiStepNode(');
    expect(script).toContain('const projectRoute = /^#\\/projects\\/');
    expect(script).toContain('async function debugApiCase()');
    expect(script).toContain('async function loadBatchHistory(projectId = activeProjectId)');
    expect(script).toContain('`/api/batches?projectId=${encodeURIComponent(projectId)}`');
    expect(script).toContain('async function loadProjects()');
    expect(script).toContain('function toggleVisibleCases()');
    expect(script).toContain('async function deleteSelectedCases()');
    expect(script).toContain('async function runSavedCase(testCase)');
    expect(script).toContain('async function deleteSavedCase(testCase)');
    expect(script).toContain('`/api/batches/${batch.id}/report`');
    expect(script).toContain("'/api/projects'");
    expect(script).toContain('#/projects/');
    expect(stylesheet).toContain('.api-request { grid-template-columns: 28px minmax(0, 1fr); }');
    expect(stylesheet).toContain('.case-row-actions');
    expect(stylesheet).toContain('.api-request .step-content { min-width: 0; }');
    expect(script).toContain("target === 'api' ? '接口用例编排' : 'Web UI 用例编排'");
    expect(script).toContain('function updateEditorBreadcrumb()');
    expect(script).toContain('<b>接口测试执行</b><small>结构化 POST 请求 · 断言、变量提取</small>');
    expect(script).not.toContain('CMS 加密接口执行');
    expect(stylesheet).toContain('@media (max-width: 760px)');
    expect(stylesheet.length).toBeGreaterThan(5000);
  });
});
